### PR TITLE
Re-organize file structure for easier development, and adjust CMakeLists accordingly

### PR DESCRIPTION
**Pull request by qwertychouskie**
This, plus a change in the code that I have locally, allows Cubosphere to be launched without installing system-wide.

Note that although CMakeLists.txt should behave the same, bugs are always possible.

The code I'm using in `main.cpp`, to be pushed soon:
```
#ifdef __GNUC__
#include <experimental/filesystem>
namespace filesystem = std::experimental::filesystem;
#else
#include <filesystem>
namespace filesystem = std::filesystem;
#endif
```
...
```
if (filesystem::exists(filesystem::path(dir+PlattformFilename("/data/boot.lua")))) {
		SetDataDir(dir+PlattformFilename("/data"));
	}
	else if (filesystem::exists(filesystem::path(dir+PlattformFilename("/../data/boot.lua")))) {
		SetDataDir(dir+PlattformFilename("/../data"));
	}
	else if (filesystem::exists(filesystem::path(dir+PlattformFilename("/../../data/boot.lua")))) {
		SetDataDir(dir+PlattformFilename("/../../data"));
	}
	else if (filesystem::exists(filesystem::path(dir+PlattformFilename("/../../../data/boot.lua")))) {
		SetDataDir(dir+PlattformFilename("/../../../data"));
	}
#ifdef DATADIR
	else if (filesystem::exists(filesystem::path(DATADIR))) {
		SetDataDir(dir+PlattformFilename(DATADIR));
	}
#endif
	else {
		Log::fatal("Init", "Could not find data directory!");
	}
	Log::info("Init", "Found assets directory: %s", g_DataDir().c_str());
```

### CODE REVIEW

**Comment by v1993** [comment]
Why do you reorganize stuff this way?

While I do appreciate some fixes in CMake, IMHO current structure is clearer. Why do you install entire folder contend as zip? You don't wanna pack CMakeLists, another copy of boot.lua and some other stuff after all!

**Review by v1993 — CHANGES_REQUESTED** [review]
I don't appreciate these changes: you can pack stuff same way with old structure.

**Comment by qwertychouskie** [comment]
@v1993 The reason is that the current structure can't be used by the game, running the game requires installing it system wide. (!)  People shouldn't need to `sudo make install` just to run the game after compiling.  Maintaining a low barrier to entry is important if we want to attract new contributors.

Would it be better if I just removed zip support for the main assets?  Zip only really seems useful for mods and additions anyways, the main assets probably don't need it.

**Comment by v1993** [comment]
Are you planning to ship packages? If yes, there is no such thing as compiling and installing after it at all. If no, I have no idea why users would run game in-place (binary is in `build/` dir anyways!). As for system-wide install, I often install things into `~/.local`.

I'm not working on cobosphere anyways and when will, entire directory structure will be redone from scratch. So I think that it is probably better to let you maintain fork of both data and code repos. However, it's all up to you.

**Comment by qwertychouskie** [comment]
This is for developers (like me), not really end-users.  Requiring a `make install` every time you tweak an asset or Lua script, even if you set the install prefix to e.g. `~/.local`, is an unnecessary hurdle to jump through.  Attracting devs is super important to the long-term success of Cubosphere, let's make the barrier to entry as low as possible.

(Though it also helps Windows packaging, I can just place the exe, dlls, and data folder together, and it will launch without needing to define DATADIR during building.  This is important because most installers on Windows let you select where to install to, so an absolute DATADIR won't work.)

Once this is merged, I can push some of my code changes, including Windows build support.  After that I plan on posting in the FreeGameDev forums that "Cubosphere needs your help!"  I really need a dev familiar with Windows debugging to help with getting the Windows port working.

And if you aren't currently working on Cubosphere, and are re-doing the structure when you start the re-do, you might as well merge it.  :)

Also, can you create a `dependencies` repo under https://github.com/cubosphere/ and give me write access to it?  I need a repo for the Windows deps package, like https://github.com/supertuxkart/dependencies.  (I'd rather keep the binary deps out of the code repo for size reasons. :)

**Comment by v1993** [comment]
Well, I'll most likely never work on (this) cubosphere because of tons of its flaws. I'll just give you full access to cubosphere organisation. Do whatever you want. Good luck! Just please, don't overwrite git history so full version including my commits will stay available.

P.S.: as for install step, I use KDevelop which is capable of building and installing before running your executable, so I never considered this a problem.

**Comment by qwertychouskie** [comment]
Thanks!  I'll be careful. :)

I'm closing this PR and pushing the commit directly, to keep the git history clean of unnecessary merge commits. :)

**Pull request closed without merging**
